version: '3.8'
services:
  db:
    image: postgres:15
    container_name: auction-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auction_db
    ports:
      - "5432:5432"